---
# tasks file for icinga_service_template

- name: see if service template already exists
  uri:
    headers:
      Accept: application/json
    validate_certs: no
    url: "{{ icinga_host }}/director/service?name={{ item.object_name }}"
    method: GET
    user: "{{ icinga_user }}"
    password: "{{ icinga_pass }}"
    return_content: yes
  register: service_template_presence
  with_items: "{{ templates }}"
  failed_when: false

- name: create service template if it does not exist
  uri:
    headers:
      Accept: application/json
    validate_certs: no
    url: "{{ icinga_host }}/director/service"
    method: POST
    user: "{{ icinga_user }}"
    password: "{{ icinga_pass }}"
    body: "{{ item.item | to_json }}"
    body_format: json
    return_content: yes
  register: service_template_created
  with_items: "{{ service_template_presence.results }}"
  when: "'error' in item.content"
  changed_when: service_template_created.status == 201
  failed_when: service_template_created.status != 201
  notify: deploy
  
- name: modify service template if it does exist
  uri:
    headers:
      Accept: application/json
    validate_certs: no
    url: "{{ icinga_host }}/director/service?name={{ item.item.object_name }}"
    method: POST
    user: "{{ icinga_user }}"
    password: "{{ icinga_pass }}"
    body: "{{ item.item | to_json }}"
    body_format: json
    return_content: yes
  register: service_template_modified
  with_items: "{{ service_template_presence.results }}"
  when: "'error' not in item.content"
  changed_when: service_template_modified.status == 200
  failed_when: service_template_modified.status !=  200 and service_template_modified.status != 304
  notify: deploy
